server:
  allowed_origin: *
  methods: GET, POST, PUT, DELETE
  headers: content-type, custom-token, iduser
  content_type: application/json
database:
  db_host: db
  db_port: 3306
  db_user: frix
  db_password: 123456
  db_name: isft