-- MySQL Script generated by MySQL Workbench
-- mié 03 may 2023 22:06:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `isActive` TINYINT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_data` (
  `iduser_data` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser_data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_user_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_user_data` (
  `user_data_iduser_data` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  INDEX `fk_user_has_user_data_user_data1_idx` (`user_data_iduser_data` ASC) VISIBLE,
  INDEX `fk_user_has_user_data_user1_idx` (`user_iduser` ASC) VISIBLE,
  UNIQUE INDEX `user_data_iduser_data_UNIQUE` (`user_data_iduser_data` ASC) VISIBLE,
  UNIQUE INDEX `user_iduser_UNIQUE` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_data_user_data1`
    FOREIGN KEY (`user_data_iduser_data`)
    REFERENCES `mydb`.`user_data` (`iduser_data`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_data_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `idgroup` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NULL,
  PRIMARY KEY (`idgroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group_has_user` (
  `idgroup_has_user` INT NOT NULL,
  `group_idgroup` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idgroup_has_user`),
  INDEX `fk_group_has_user_group1_idx` (`group_idgroup` ASC) VISIBLE,
  INDEX `fk_group_has_user_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_group_has_user_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `mydb`.`group` (`idgroup`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
